### ISSUE TITLE
template auto parameter should not pass type 

### ISSUE THREAD

**Issue by huangminghuang** [AntelopeIO/eos-vm#3]
In function_traits.hpp:105, the template function `is_callable_v` is declared to accept an auto parameter; however, the calling side is passed a type parameter `decltype(fn)` which causes a compiler error on Apple clang version 14. The code should be changed to `if constexpr (is_callable(fn))` instead.

**Comment by heifner** [comment]
Related: https://github.com/EOSIO/eos-vm/pull/210
